REQUIRE
docs/src/index.md
docs/src/tutorials/latexify.md
src/Latexify.jl
src/latexalign.jl
src/latexarray.jl
src/latexify_function.jl
src/latexoperation.jl
src/latextabular.jl
src/md.jl
src/mdtext.jl
test/latexalign_test.jl
test/latexarray_test.jl
test/latexify_test.jl
test/latexinline_test.jl
test/latexraw_test.jl
test/mdtable_test.jl
test/runtests.jl

Admittedly, this merge is a bit of a mess (I have worked on too many things at once). But, the main feature that this provides is the ability of `latexify()` to handle all kinds of input, and for the user to be able to specify what output they want using a keyword argument.
previously:
```julia
latexarray([1,2,3])
```
now:
```julia
latexify([1,2,3]; env=:array)
```
As before, `latexify` will try to infer the desired output based on the input. But now you can override the defaults. 
This merge brings some additional changes (which really should have been developed in separate branches): 
-  Make the tests actually use Base.Test.
-  Add support for dicts with latexarray.
-  Add ability to generate starred array and align environments (`\begin{align*}....).
-  Add kwarg `bracket=false` to …

Allow access to all functions via `latexify` and kwargs.

---

docs/src/tutorials/DiffEqBiological.md
src/Latexify.jl
src/chemical_arrows.jl
src/latexify_function.jl
test/REQUIRE
test/chemical_arrows_test.jl
test/runtests.jl

This adds support for latexifying/rendering chemical arrow notation from DiffEqBiological's reaction_networks.

Add chemical reaction arrow notation support.

---

docs/src/tutorials/DiffEqBiological.md
src/Latexify.jl
src/chemical_arrows.jl
test/chemical_arrows_test.jl

While katex supports `\xleftrightharpoons`, it seems that MathJax does not. I'm therefore reverting back to using the `mhchem` approach.

Revert arrows

---

docs/src/tutorials/DiffEqBiological.md
src/latexalign.jl
test/latexalign_test.jl
test/latexify_test.jl

DiffEqBiologicals reaction networks result in a lot of ugly `+ (-1 * ...)` terms. Previously, this was solved by letting SymEngine reduce the expressions. Here, I add a non-symbolic option to do the same. 
The main benefit of this is that the order of the terms in the output becomes predictable. 
Before merging:

Improve non-symbolic handling of reaction networks.

---

src/latexoperation.jl
test/latexraw_test.jl

See #33 
This strips all dots and basically ignores broadcasting.
I cringe a bit as a mathematician since this allows for misrepresentations without raising errors. However, I agree that this is more useful than an error, and I will defer the correctness of the mathematics to the user. 
This also adds infix support for (chained) comparison operations:
```julia
latexify(:(a .<= b .< c .== a))
```
$\left( a \leq b \lt c = a \right)$

Update support for broadcasted operations. 

---

docs/src/index.md
docs/src/table_generator.jl
src/Latexify.jl
src/latexalign.jl
src/latexarray.jl
src/latexinline.jl
src/latexraw.jl
src/latextabular.jl
src/mdtable.jl
src/mdtext.jl
test/latexalign_test.jl
test/latexarray_test.jl
test/latexinline_test.jl
test/latexraw_test.jl
test/mdtable_test.jl

As per issue #32.
Add a kwarg `fmt` which is passed along to Printf for number formatting.  This enables for example scientific notation to be used.

Formatted numbers

---

src/plugins/DiffEqBiological.jl
test/chemical_arrows_test.jl

Fix an index inconsistency for chemical arrows. Closes #41.
Also, remove an excessive `\\` which causes enumeration of an empty arrow at the end of the expression.

Index consistency fix

---

src/Latexify.jl
src/latexraw.jl
test/latexraw_test.jl

Convert for example `"α"` to `"\alpha"`. Closes #35. 
Thanks to @isaacsas for pointing out where to find a unicode to latex correspondence dictionary.

Add unicode-to-LaTeX conversion.

---

docs/src/table_generator.jl
src/mdtable.jl
src/mdtext.jl
test/mdtable_test.jl

Underscores can denote italics in markdown. Sometimes this is not what you want. This adds a kwarg to escape the underscores.

Add escape_underscore kwarg for Markdown.

---

docs/src/table_generator.jl
src/plugins/DiffEqBiological.jl
test/latexalign_test.jl

`clean_substitutions` has been moved to DiffEqBiological itself. This
creates a kwarg to toggle the cleaning within latexify and it generates
a warning if improperly used.

Disable clean_substitutions by default.

---

docs/src/table_generator.jl
src/latexoperation.jl
src/latexraw.jl
src/plugins/DiffEqBiological.jl
src/plugins/ParameterizedFunctions.jl
src/plugins/SymEngine.jl
test/cdot_test.jl
test/chemical_arrows_test.jl
test/runtests.jl

This adds a `usecdot` kwarg to `latexify`. The default is true, which should not result in any changes in generated Latex, but if set to `false` will cause `latexraw` to just insert a single space within products instead of a \cdot.
I tried to forward kwargs everywhere it looked like this would change behavior, but please do let me know if I've missed anything and I can update the PR.

add usecdot kwarg

---

docs/make.jl
docs/src/arguments.md
docs/src/index.md
docs/src/table_generator.jl
src/Latexify.jl
src/latexequation.jl
src/latexify_function.jl
test/latexequation_test.jl
test/runtests.jl

When using Weave.jl, I found myself missing the option of outputting a 
```latex
\begin{equation}
...
\end{equation}
```
environment. This PR remedies this.

Add support for env=:equation.

---

src/latexarray.jl
test/cdot_test.jl
test/latexarray_test.jl
test/unicode2latex.jl

See #67. 
This is a breaking change and it affects how vectors and tuples are represented in the `:array` environment.

Redefine default orientation vectors in env=:array

---

src/unicode2latex.jl
test/unicode2latex.jl

```
julia> latexify(:αβa)                                                                  
L"$\alpha{\beta}a$" 
```
This avoids the error `\betaa`

Fix broken mid-word unicode. Closes #79.

---

Project.toml
src/Latexify.jl
src/numberformatters.jl

Ensures that the same printf number formatting operation does not need to be re-compiled for every single call. 
This adds a dependency to Formatting.jl
Closes #90

Use Formatting.jl to speed up printf.

---

Project.toml
docs/src/index.md
src/Latexify.jl
src/latexoperation.jl
src/macros.jl
src/utils.jl
test/macros.jl
test/runtests.jl

Poor practice, but this PR contains two separate new features.
One is the exported function `render` which tries to render a LaTeXString using lualatex and open the result in an external viewer. Useful for rendering things when in the REPL.
The other is a macro `@latexify` which can be used to directly latexify one-liner Julia functions.
```julia
julia> @latexify f(x, y=2) = x^2 + y
$\mathrm{f}\left( x, y = 2 \right) = x^{2} + y$
```
This macro call will also define `f` as expected.
No documentation or test yet.

Add macro for latexifying one-liner functions and add external rendering.

---

src/Latexify.jl

There's no reason to use `joinpath` here since this syntax is supported across different OSs, and it has the potential to cause problems with tools that try to statically understand `include`s.

Use standard syntax for including files

---

src/latexraw.jl

`latexraw(x::Rational{T<:Integer})` and `latexraw(z::Complex{T<:Real})` now recursively use `latexraw(x::T)`, so that for instance `latexify( Complex(1//3,1//2) )` evaluates to `L"$\frac{1}{3}+\frac{1}{2}\textit{i}$"`.

Make latexraw recursive for Rational and Complex args

---

src/latexoperation.jl
test/latexraw_test.jl

Pardon four changes bundled into one PR. The main contribution is adding support to translate Julia conditional blocks (and ternary ifs) to LaTeX `cases` environments. See an example with stressing cases here:
- PDF: https://github.com/mossr/TeX.jl/blob/master/test/pdf/latexify_cases.pdf
- Code: https://github.com/mossr/TeX.jl/blob/master/test/test_latexify_cases.jl
The other minor contributions are:
1. Add support for logical operators: `\wedge` for `&&`, `\vee` for `||`, and `\neg` for `!`
2. Changed `\lt` and `\gt` to `<` and `>` (these commands were not defined using standard `amsmath`)
3. Skip applying `\mathrm` to function operator names when they're single characters (e.g., `f(x)` should be math-italicized and `loss(x)` should not)
By the way, great work with this package! It was …

Support {cases} environments and logical operators

---

Project.toml
appveyor.yml
src/latexoperation.jl
src/latexraw.jl
test/macros.jl

This fixes an issue where `convertSubscript` was not always applied to
symbols in expressions.

Ensure application of latexraw on leaf nodes.

---

src/latexify_function.jl

Previously, the LaTeXString was surrounded by an inline env. 
This fixes the latexification of ModelingToolkit Systems, https://github.com/SciML/ModelingToolkit.jl/pull/626

Ensure that `latexify(s::LaTeXString) == s`.

---

Project.toml
src/latexalign.jl
src/latexoperation.jl
test/latexalign_test.jl
test/latexraw_test.jl

- fix handling of `@__dot__` in an expression.
- fix handling of zero-argument function calls in expressions (like `eps()`)
- allow align `separator` to be an iterable with one entry per row of the align env.

Minor fixes

---

src/latexraw.jl
test/latexraw_test.jl

Fix so that 
```julia
latexify(:(a = [x/y 1; 2 3]))
```
no longer errors but instead gives the expected
$a = \left[
\begin{array}{cc}
\frac{x}{y} & 1 \\\\
2 & 3 \\\\
\end{array}
\right]$

Fix latexification of arrays of expressions inside expressions.

---

src/latexarray.jl

Uses `latexify(..., env=:raw)` rather than `latexraw(...)` to invoke latexrecipes on the elements of arrays. 
(I need this for UnitfulLatexify)

Recursive array latexification

---

src/Latexify.jl
src/latexalign.jl
src/latexarray.jl
src/latexbracket.jl
src/latexequation.jl
src/latexify_function.jl
src/latexinline.jl
src/latexoperation.jl
src/latexraw.jl
src/latextabular.jl
src/md.jl
src/mdtable.jl
src/plugins/DataFrames.jl
src/plugins/DiffEqBiological.jl
test/utils_test.jl

(I know you're working on a big rework, so depending on the time scale it might not be worthwhile to merge this but...)
As you know, I've wanted to sort out the recursion in this package for a while. Essentially, `latexify()` runs its arguments past the recipe system, but the subcommands like `latexraw` don't. I've previously tried replacing these by `latexify(..., env=:raw)` etc, but it turned out to be a lot of edits, and I think it makes sense to export and document the likes of `latexraw` for user use.
But if you make `latexraw(...)` a synonym for `latexify(..., env=:raw)`, you'll get stuck in a loop. *Unless*...
With this pull request, all of the exported functions are synonyms for `latexify()` with the corresponding `env` set. Internally, `latexify` uses the unexported functions …

Route exported functions through latexify

---

src/utils.jl

A super minor stability improvement. This is just cleaner.

Remove need for `replace` in HTML repr.

---

src/utils.jl

Mathjax works well enough for me not to want to maintain an additional option.

Remove katex support from HTML rendering.

---

docs/src/tutorials/rendering_latex.md
src/Latexify.jl
src/latexalign.jl
src/latexarray.jl
src/latexbracket.jl
src/latexify_function.jl
src/latexinline.jl
src/latexoperation.jl
src/latexraw.jl
src/latextabular.jl
test/cdot_test.jl
test/latexraw_test.jl
test/recipe_test.jl

Right now, `latexarray(::Array)` puts an `equation` around an array, and there is a pattern that `latexraw(x::Arr) == [ latexraw(x[1]), latexraw(x[2]), ... ]` for some of the commands. I think it would make more sense to have `latexarray` *just* do the array, `latexraw(::Array)` call `_latexarray`, and use broadcasting (`latexraw.(arr)`) to latexify each item of `arr`. This makes it easier to dispatch on `Array` types in recipes. 
`latexify(::Array)` now infers that you want to use `_latexequation`, rather than `(...) -> _latexequation(_latexarray(...))`. Since `latexraw(::Array)` now does the brackets and everything, when `_latexequation()` calls `latexraw` it will successfully latexify the array.
Small changes in usage, see how the tests have changed.
Also included: The `Symbol` change …

Shift equation<-array<-raw for arrays

---

src/plugins/DataFrames.jl

In DataFrames 0.22.6, 
```
convert(Matrix, df)
```
was [deprecated](https://github.com/JuliaData/DataFrames.jl/blob/73ca8f190bffcba8cd78ef911d62562357be1cc8/NEWS.md#dataframes-v0226-release-notes) in favor of 
```
Matrix(df)
```
You can see that the warnings did occur for the most [recent CI run on Julia 1](https://github.com/korsbo/Latexify.jl/runs/2227953398). I noticed the warnings because I'm using `jldoctest` which will fail when warnings occur.

Avoid deprecated convert function

---

src/latexoperation.jl
test/recipe_test.jl

This reverts a change I made in #146. Kind of obscure difference, it seems most of the time `i` here is either a string or some kind of scalar anyway. I can't even formulate a test for this without pulling in a dependency for Unitful. But it seems to me that the intention is not to broadcast into `i`, and this doesn't break any tests so...
(If you're curious, for some reason there are types in Unitful that are broadcastable but don't have a `length` method, so `latexraw.(i)` errors out for them. I'm opening an issue for this over there too, but irrespective I think this is the intended behaviour here)

Don't double broadcast

---

src/latexalign.jl
test/latexalign_test.jl

Fix broken align for "x = y".

---

src/latexoperation.jl
test/macros.jl

`latexify(:(@hi(x/y)))` now works and results in `"$\mathrm{@hi}\left( \frac{x}{y} \right)$"`

Add support for macros in Exprs.

---

Project.toml
src/latexify_function.jl

`latexify(:(x/y), render=true)` should now be similar to `render(latexify(:(x/y))` (except that it also returns the `LaTeXString`). 
This allows users to conveniently set `set_default(; render=true)` if they want.

Allow `render` toggling with a kwarg.

---

Project.toml
src/latexify_function.jl
src/latexinline.jl

Default kwargs are now affecting the top-level latexify call too. Previously, `set_default(; render=true)` did not work.

Fix spurious top-level recursion.

---

src/latexoperation.jl

1//2 processed as a rational number; however "1//2" in expressions processed as //(1,2). 
Effectively for latexify // in expressions should be equivalent to /.

Update latexoperation.jl to correctly process "//" in expressions as fractions

---

src/latexoperation.jl
src/latexraw.jl
test/latexraw_test.jl

This operation had to happen ahead of the recursion, but I think the result is pretty neat:
```julia
latexalign(fill(:(A), 4), [
:(prod(x_n)),
:(sum(x_n for n in :)),
:(prod(x_n for n in N)),
:(sum(x_n for n in n_0:N)),
])
```

Add sum and prod

---

docs/src/index.md
src/macros.jl
test/macros.jl

The macros (`@latexrun`, `@latexify`) were going via strings, which meant they ignored some of the latexify logic. It also meant you couldn't run them using an interpolated value (variable, function call, ...).
With this PR, the macros are operating directly on the input expressions (with some escaping logic). The star of the show is you can now do 
```julia
julia> using Latexify, Unitful, UnitfulLatexify
julia> @latexrun v = 3.5u"m/s" # This has not changed
L"$v = 3.5 \cdot \mathrm{@u\_str}\left( m/s \right)$"
julia> @latexrun v = $(3.5u"m/s") # would error before the PR
L"$v = 3.5\;\mathrm{m}\,\mathrm{s}^{-1}$"
```

Rework macros

---

docs/src/index.md
src/Latexify.jl
src/macros.jl
test/macros.jl

Adds a third printing macro `@latexdefine`, which does both of the things that `@latexrun` does (prints and evaluates expression), but also adds an equals sign and the evaluated value of the expression. This is useful for things like a Pluto workflow, where you can then in a single line get a variable's (new) definition.
```julia
julia> x = 35;
julia> @latexdefine y = 2x
L"$y = 2 \cdot x = 70$"
julia> @latexdefine y
L"$y = 70$"
```
I'm not married to the name.

Add @latexdefine macro

---

docs/src/index.md
src/macros.jl
test/macros.jl

Allow keyword arguments to be passed to the latexify macros:
```julia
julia> @latexify x = 3 env=:raw
L"x = 3"
```

Macrokwargs

---

.github/workflows/ci.yml
Project.toml
docs/src/index.md
src/macros.jl
test/macros.jl

Adds a `post` kwarg to `@latexdefine`, which gives you a bit more control of how the final rhs is formatted.
```julia
julia> @latexdefine x=3.75 post=x->round(x; sigdigits=2)
L"$x = 3.75 = 3.8$"
julia> @latexdefine x=1//2 post=float
L"$x = \frac{1}{2} = 0.5$"
julia> using Unitful, UnitfulLatexify; m = 5u"kg"; v = 10u"m/s";
julia> @latexdefine E = m*v^2/2 post=u"J"
L"$E = \frac{m \cdot v^{2}}{2} = 250.0\;\mathrm{J}$"
```
I'm mostly interested in this last one for physics material, but I think this is general enough it could be useful in different contexts as well.

Add  kwarg post

---

src/latexify_function.jl
src/latexraw.jl
src/macros.jl
src/unicode2latex.jl
src/utils.jl
test/latexify_test.jl
test/runtests.jl
test/unicode2latex.jl

- handle diacritics in a consistent manner, using escape sequences from https://en.wikibooks.org/wiki/LaTeX/Special_Characters#Escaped_codes.
```julia
julia> using Latexify
julia> latexify("éçà")
L"$\textrm{\'{e}}\textrm{\c{c}}\textrm{\`{a}}$"
```
- support `QuoteNode` in `latexraw` (e.g. when parsing `"Plots.jl"` as expr, corner case);
- add `latexify` docstring for `help?> latexify`;
- add failing expr error message when parsing fails;
- added a `parse` keyword to `_latexraw`, since `Meta.parse` can fail (especially parsing string containing diacritric markers - strings are normalized), and dispatch on `Val{true/false}` to `Meta.parse` or not.
Fix https://github.com/korsbo/Latexify.jl/issues/182.
Goes with https://github.com/JuliaPlots/Plots.jl/pull/4262.

Support diacritics (accents, ...)

---

src/utils.jl

Silent warnings on non debug output (like these ones):
```bash
[1dvipng warning: font [/usr/local/texlive/2022/texmf-dist/fonts/opentype/public/lm/lmroman12-regular.otf] at 480 dpi not found, characters will be left blank dvipng warning: unable to draw glyph 85, skipping dvipng warning: unable to draw glyph 82, skipping dvipng warning: unable to draw glyph 86, skipping dvipng warning: font [/usr/local/texlive/2022/texmf-dist/fonts/opentype/public/lm/lmroman12-regular.otf] at 480 dpi not found, characters will be left blank dvipng warning: unable to draw glyph 85, skipping dvipng warning: unable to draw glyph 82, skipping dvipng warning: unable to draw glyph 86, skipping 
```

`render`: silent `dvipng` warnings

---

src/Latexify.jl

Trying to reduce latency.
After:
```julia
Test Summary: | Pass  Total  Time
macro test    |   25     25  2.6s
Test Summary: | Pass  Total  Time
recipe test   |   13     13  4.4s
Test Summary:  | Pass  Total  Time
latexify tests |   10     10  1.3s
Test Summary:  | Pass  Broken  Total  Time
latexraw tests |  133       1    134  4.8s
Test Summary:    | Pass  Total  Time
latexalign tests |    4      4  1.3s
Test Summary:    | Pass  Total  Time
latexarray tests |   15     15  1.5s
Test Summary:       | Pass  Total  Time
latexequation tests |    2      2  0.1s
Test Summary:      | Pass  Total  Time
latexbracket tests |    2      2  0.0s
Test Summary:     | Pass  Total  Time
latexinline tests |    1      1  0.3s
Test Summary:      | Pass  Total  Time
latextabular tests |   11     11  7.3s …
```

opt-level and max-methods = 1

---

.github/workflows/benchmark.yml

There's a permissions issue in getting benchmarks posted as a comment on PRs. This way, you can also check the benchmark results in the CI log.

Print benchmark results in log

---

src/latexoperation.jl
test/latexraw_test.jl

```julia
@latexify  x-> x^p
```
becomes
```julia
L"$x \mapsto x^{2}$"
```

Support for anonymous functions

---

Project.toml
docs/Project.toml
docs/src/index.md
src/Latexify.jl
src/numberformatters.jl
test/numberformatters_test.jl

Also eliminated the need to do @eval at run-time just for numeric formatting, which also eliminates the need for Printf as a dependency.

Fix potential bugs by switching from Formatting.jl to Format.jl

---

docs/Project.toml
docs/make.jl
docs/src/functions/latexraw.md
docs/src/tutorials/latexalign.md
docs/src/tutorials/parameterizedfunctions.md

The PR resolves the errors of the docs builds.

Fix docs errors

---

src/latexarray.jl
test/latexarray_test.jl

Solves #284 
Higher-dimensional tensors cannot be simply printed, so this PR throws an error. A bit more informative than the indexing error it would have caused before.

Disallow tensors

---

docs/src/tutorials/recipes.md
src/latexraw.jl
src/recipes.jl
test/recipe_test.jl

Previously, recipes had no way of affecting the previous operation. With this (somewhat ugly) change, a type that fundamentally represents for instance a multiplication or sum can tell latexify, so that things like parentheses work out right.
Part of fixing #280

Allow recipes to set previous operation

---

ext/DataFramesExt.jl
ext/SymEngineExt.jl

I've wanted to do this for a while, and it recently became much easier. Low priority, but maybe at least worth keeping in mind if we ever need to change either extension.
If this breaks something, that something was not in the tests.

Convert extensions to recipes

---

docs/src/table_generator.jl
src/latexify_function.jl
src/mdtable.jl
src/mdtext.jl
test/plugins/DataFrames_test.jl

`mdtable` and `mdtext` were not using the recipe system (https://github.com/korsbo/Latexify.jl/pull/263#issuecomment-2215507951). 
Now they are. This is a direct parallel to how all other environments work.

Run mdtable and mdtext through latexify

---

src/unicode2latex.jl
test/unicode2latex.jl

I would guess that `ȧ` and `â` are more likely to be the mathematical ``\dot{a}`` and ``\hat{a}`` than the text diacritics. Maybe this should be configurable, but I cannot imagine that many people are using the `\textnormal` versions.
Closes #179, Closes #282, Closes #243

Dots, hats, tildes and bars

---

docs/src/table_generator.jl
docs/src/tutorials/Catalyst.md
docs/src/tutorials/latexalign.md
docs/src/tutorials/latexify.md
docs/src/tutorials/parameterizedfunctions.md
src/latexalign.jl
test/latexalign_test.jl
test/latexraw_test.jl
test/recipe_test.jl

Aligned equations were separated by `=&`, which produces an unintended space (https://github.com/SciML/ModelingToolkit.jl/issues/2894) around the equality sign. This changes them to be separated by `&=` instead, which is the most common way to do it and removes the unindented space. See also [this StackExchange post](https://tex.stackexchange.com/questions/41074/relation-spacing-error-using-in-aligned-equations).
Does this have any unintended side effects I am not thinking about?

Separate aligned equations correctly

---

src/Latexify.jl
src/utils.jl
test/utils_test.jl

Closes #274 
Implement an error type for rendering errors. On latex error moves the log file to the same place as the output file, quotes the error and recommends to read the log file for information.

Informative error messages for failed renders

---

src/recipes.jl
test/recipe_test.jl

Allow `nothing` as a sentinel value in recipes

---

src/latexoperation.jl
src/latexraw.jl
test/latexraw_test.jl

Make sure indices of arrays of arrays print correctly.

Fix doubly-indexed arrays

---

docs/src/index.md
docs/src/table_generator.jl
src/default_kwargs.jl
src/latexoperation.jl
test/cdot_test.jl
test/latexify_test.jl

Follow-up to https://github.com/korsbo/Latexify.jl/pull/323; see discussion there.
@gustaphe I figured the simplest way of handling the deprecation of `cdot` in code is to convert it to the equivalent `mult_symbol`. This means `cdot` takes precedence over `mult_symbol` in the event that they are both set, which is the opposite of what we agreed. I can argue both ways; if you think it is more natural for `mult_symbol` to take priority, or there is anything else, I am happy to update it.

Replace boolean cdot keyword argument in favor of more flexible mult_symbol string

---

src/unicode2latex.jl
test/unicode2latex.jl

Julia seems to have up to four possible levels of \dot-ting.
I encountered errors when rendering some of these that were not implemented.

Parse all four levels of \dot

---

src/latexoperation.jl
test/latexraw_test.jl

I'm surprised how intransparently the parser differentiates broadcasting (`f.(x)`) and property/field access (`A.x`). Here's an implementation that solves #321 (sorry, just recently noticed this one).
close #321

Differentiate between broadcasting and property access

---

src/latexarray.jl
test/latexarray_test.jl

Close #318 
Amsmath matrix styles don't need alignment strings, so this PR removes them. Also added a couple of array styles for consistency.

Add more array styles, fix amsmath ones

---

docs/src/index.md
docs/src/tutorials/latextabular.md
src/Latexify.jl
src/latextabular.jl
src/numberformatters.jl
src/utils.jl
test/latextabular_test.jl
test/numberformatters_test.jl

Create a number formatter that outputs siunitx commands (`\num`, typically). Might seem a little like overkill for `Latexify`, but for `UnitfulLatexify` this will make things more unified. And this will link into the `Unitful` extension in `Plots`.
```julia
julia> @latexify x=1.375 fmt=SiunitxNumberFormatter()
L"$x = \num{1.375}$"
```
Needed a way to replace `gs` with `gswin64c` on Windows for documentation, so I'm sneaking that in here too.

Siunitx formatter

---

src/Latexify.jl
src/internal_recipes.jl
src/latexarray.jl
src/latexoperation.jl
src/symbol_translations.jl
test/latexarray_test.jl
test/latexraw_test.jl

Close #315 
This makes it so ranges like `1:3` are (optionally) turned into $1 \mathrel{\ldotp\mkern-2.5mu\ldotp} 3$ rather than 
```math
\left[
\begin{array}{c}
1 \\
2 \\
3
\end{array}
\right]
```
. Step ranges like `1:2:5` do not have as standardized a math syntax, but I also include the option to have it shown as $1 \underset{2}{\mathrel{\ldotp\mkern-2.5mu\ldotp}} 5$. The kwargs `expand_ranges` and `expand_step_ranges` can disable both or one of these contractions, respectively.
When part of an expression, I have elected to not run the calculation to figure out the expanded vector, so `:(1:2:5)` always becomes $1 \underset{2}{\mathrel{\ldotp\mkern-2.5mu\ldotp}} 5$. Even if this is not standard notation, it is better than $:(1, 2, 5)$ as we had before.
Any arithmetic on the end points …

Add range operator

---

Project.toml
docs/src/index.md
ext/TectonicExt.jl
src/Latexify.jl
src/utils.jl
test/cdot_test.jl
test/utils_test.jl

Close #236 
A lightweight requirement for CI purposes etc.

Add Tectonic extension
