korsbo/Latexify.jl

docs/src/tutorials/DiffEqBiological.md, src/chemical_arrows.jl, test/chemical_arrows_test.jl
-  Add ability to expand DiffEqBio functions into their mathematical
expression.
-  Change ouput environment to \begin{equation}.
-  Add linebreaks to output.
=> Improve chemical_arrows.

.travis.yml, src/latexoperation.jl, test/latexalign_test.jl, test/latexraw_test.jl
A bug resulted in the wrong sign of some terms. Example:
1 - ( 1 - 1)
resulted in :
1 - 1 - 1
This commit fixes that and updates tests.
Closes #21
=> Fix bug with nested subtractions.

src/Latexify.jl, src/latexoperation.jl, src/latexraw.jl, test/latexraw_test.jl
=> Fix unicode2latex of sub/superscripts.

src/latexraw.jl, src/plugins/DataFrames.jl, test/plugins/DataFrames.jl, test/runtests.jl
Minor changes which increase readability and stability.
-  Add support for making `:array`s from DataFrames.
-  Add support for Chars.
-  Add tests for DataFrames. 
-  Improve code readability.
=> Expand support and tests for DataFrames.

src/latexalign.jl, src/latexarray.jl, src/latexify_function.jl, src/latexinline.jl, src/latexraw.jl, src/md.jl, src/mdtable.jl, test/latexalign_test.jl, test/latexarray_test.jl, test/mdtable_test.jl
=> Add support for Tuples.

.travis.yml, README.md, docs/src/index.md, src/Latexify.jl, src/default_kwargs.jl, src/latexify_function.jl, test/latexify_test.jl
=> Add ability to set default keyword arguments.

.travis.yml, appveyor.yml, docs/make.jl, docs/src/table_generator.jl, docs/src/tutorials/recipes.md, src/Latexify.jl, src/latexarray.jl, src/latexify_function.jl, src/latexinline.jl, src/latexraw.jl, src/recipes.jl, test/cdot_test.jl, test/latexarray_test.jl, test/recipe_test.jl, test/runtests.jl, test/unicode2latex.jl
Merge to master for next minor release.
=> Next minor release

Project.toml, src/latexarray.jl, src/latexify_function.jl, src/latexraw.jl, test/latexarray_test.jl, test/latexify_test.jl
=> Allow arrays in expressions

Project.toml, docs/src/table_generator.jl, src/latexalign.jl, test/latexalign_test.jl
Allows the specification of which rows to output in an align.
=> Add `rows` kwarg to latexalign.

src/latextabular.jl, test/latextabular_test.jl
It now can automatically insert the booktabs-package commands `\toprule`, `\midrule` and `\bottomrule`.
=> Add booktabs support

Project.toml, src/latexoperation.jl, test/macros.jl
allows
```julia
@latexify f(x::Number) = x
```
=> Add support for type annotations.

Project.toml, src/latexoperation.jl, test/macros.jl
```julia
@latexify f(::Number) = "hello"
```
should now work.
=> Add support for latexifying annotations like `::SomeType`.

src/utils.jl
Add support for rendering latex in the VSCode plot pane using HTML + Mathjax/Katex. 
Add more "clever" default `render` display options based on what's displayable in your environment.
=> Add HTML rendering for VSCode.

src/latexoperation.jl, test/latexraw_test.jl
=> Fix exponentiation parentheses.

Project.toml, src/latexraw.jl
Fixes https://github.com/JuliaSymbolics/Symbolics.jl/issues/91
=> Discard potential error from `isinf` check.

src/Latexify.jl
Add macros for easily generating latexify tests and appending them to a specified file.
=> Add test-file generation support.

src/latexoperation.jl
=> Enforce latexoperation `String` return type.

src/latexalign.jl, src/latexarray.jl, src/latexify_function.jl, src/latextabular.jl, src/mdtable.jl, src/plugins/ParameterizedFunctions.jl, src/utils.jl, test/latexarray_test.jl, test/latextabular_test.jl
=> Fix `cat` reduction of single-element iterators.

Project.toml, src/latexalign.jl, src/latexarray.jl, src/latexbracket.jl, src/latexequation.jl, src/latexify_function.jl, src/latexinline.jl, src/latexraw.jl, src/latextabular.jl, src/plugins/DiffEqBiological.jl
=> Fix top-level recursion bug.

Project.toml, src/latexinline.jl
Sigh. I seem to have left one behind in the last hotfix release. Two hotfixes in an hour. A new record.
=> Fix spurious top-level recursion.

Project.toml, src/latexoperation.jl, test/latexraw_test.jl
Was
```
julia> @latexify 1*(1 .+ 1)
L"\$1 \cdot 1 + 1\$"
```
=> Fix .+/.- parenthesis bug

Project.toml, docs/src/index.md, src/utils.jl, test/utils_test.jl
Now you can `render` LaTeXStrings with user supplied classes and packages.
=> Provide packages to render

Project.toml, docs/src/table_generator.jl, src/latexarray.jl, src/latextabular.jl, src/mdtable.jl, test/latexarray_test.jl, test/latextabular_test.jl, test/mdtable_test.jl
Allow vectors of adjustment symbols, and make adjustment affect mdtable.
=> Adjustment

README.md, docs/make.jl, docs/src/tutorials/notebooks.md, docs/src/tutorials/rendering_latex.md
=> [documentation] Include some tips for working in a notebook

src/latexoperation.jl, test/latexraw_test.jl
=> Support binomial

docs/src/table_generator.jl, src/latexarray.jl, test/latexarray_test.jl
I realized I had this branch that would close #242 kicking around.
=> More flexible arrays and brackets

.github/workflows/benchmark.yml, .gitignore, benchmark/Project.toml, benchmark/benchmarks.jl
An idea after #244 . I don't see a way to have it report loading time, sadly no loading time report. And we probably want to be running a bigger array of benchmarks, but I wanted to try it out.
=> BenchmarkCI

Project.toml, ext/DataFramesExt.jl, ext/DiffEqBiologicalExt.jl, ext/ParameterizedFunctionsExt.jl, ext/SymEngineExt.jl, src/Latexify.jl
This should help some instances where things want to precompile code. From my benchmarks there is a de minimis reduction in load time.
=> Switch to Weak dependencies on 1.9+

Project.toml, docs/src/table_generator.jl
A typo caused #267 , and I can't really see what caused #266 but just bumping the number might fix it?
=> Fix a docs source typo + bump version

.github/workflows/ci.yml, Project.toml, src/unicode2latex.jl
Required for Plots on `nightly` (fix `Iterators.Stateful` iteration), and test upcoming `1.11`.
Building docs were already broken before, left for another PR.
cc @korsbo.
=> fix nightly

src/latexarray.jl, test/latexarray_test.jl
Fix https://github.com/korsbo/Latexify.jl/issues/284#issuecomment-2061040102.
=> Update error handling on 0-dim array

ext/DataFramesExt.jl, test/plugins/DataFrames_test.jl
=> Fix dataframe 'head' argument
